# Campaign List Segmentation Project: Identifying Target Audiences

This project aims to create three distinct campaign list categories tailored for specific audiences within the MasterList data. By analyzing SIC codes, job titles, and other key identifiers, we will segment the data into targeted lists for:

1. **Premium Campaign List:**

   - Prioritized based on specific SIC codes (7311, 8721, 8748, 7319, 8742) and primary industries (Advertising, media, marketing, business consulting, tax services, financial services, wealth planning).
   - Focuses on senior-level positions (excluding "staff") across various job types.
   - Requires valid business email addresses for direct outreach.

2. **Conversational AI List:**

   - Compiled based on contact information with valid phone numbers.
   - Includes job types excluded from the Premium Campaign List (e.g., interns, professors, scientists, engineers).

3. **Social Media Campaign List:**

   - Leverages job types not targeted in the Premium Campaign List (e.g., social media-related roles).
   - Ideal for broader reach and engagement through social media platforms.

By segmenting the MasterList data in this way, we can create more focused and effective campaigns for each distinct audience group, maximizing engagement and campaign ROI.

**Key benefits:**

- Increased audience relevance: Tailored messaging for specific needs and interests.
- Improved campaign performance: Higher engagement and conversion rates.
- Cost-effective targeting: Optimized resource allocation for each campaign.

In [1]:
#Import required Packages
import pandas as pd
import numpy as np
from Adfunctions import *
from validate_functions import *
pd.set_option('display.max_rows', 100)

In [2]:
#Vew list of all functions in the Adfunctions.py file
import inspect
import Adfunctions
# List all functions in the module
functions_list = inspect.getmembers(Adfunctions, inspect.isfunction)
#view all list of functions in the Adfunction package
functions_list

[('count_duplicates', <function Adfunctions.count_duplicates(df)>),
 ('df_to_excel_openpyxl',
  <function Adfunctions.df_to_excel_openpyxl(dfs, file_path, sheet_names=None)>),
 ('drop_rows_with_hyphen',
  <function Adfunctions.drop_rows_with_hyphen(df, columns)>),
 ('enrich_phone_numbers', <function Adfunctions.enrich_phone_numbers(df)>),
 ('filter_and_label_valid_addresses',
  <function Adfunctions.filter_and_label_valid_addresses(df)>),
 ('filter_by_seniority',
  <function Adfunctions.filter_by_seniority(df, exclude_levels=None)>),
 ('filter_by_sic_codes',
  <function Adfunctions.filter_by_sic_codes(df, target_sic_codes)>),
 ('filter_by_target_industries',
  <function Adfunctions.filter_by_target_industries(df, target_industries)>),
 ('filter_by_valid_business_email',
  <function Adfunctions.filter_by_valid_business_email(df, column_name='BUSINESS_EMAIL_VALIDATION_STATUS')>),
 ('filter_by_valid_business_personal_email',
  <function Adfunctions.filter_by_valid_business_personal_email(df, validation_column='BUSINESS_EMAIL_VALIDATION_STATUS', business_email_column='BUSINESS_EMAIL', personal_email_column='PERSONAL_EMAIL')>),
 ('filter_usa_states', <function Adfunctions.filter_usa_states(df)>),
 ('filter_valid_personal_emails',
  <function Adfunctions.filter_valid_personal_emails(df)>),
 ('get_data', <function Adfunctions.get_data(file_path, **kwargs)>),
 ('list_files_in_folder',
  <function Adfunctions.list_files_in_folder(folder_path)>),
 ('liveramp_formatter', <function Adfunctions.liveramp_formatter(df)>),
 ('merge_csv_files',
  <function Adfunctions.merge_csv_files(folder_path, output_file, columns_to_check=None)>),
 ('save_df_to_csv', <function Adfunctions.save_df_to_csv(df, file_name)>),
 ('sort_and_filter_jobs',
  <function Adfunctions.sort_and_filter_jobs(df, keywords_to_exclude)>),
 ('split_columns_by_separator',
  <function Adfunctions.split_columns_by_separator(df, columns, separator=',', keep_non_missing_only=True, drop_duplicates=True)>)]

In [3]:

# Print the data (optional)
df= get_data('./raw_data/Traffic-Convert Agencypartners-Master - Traffic-Convert Agencypartners-MasterList.csv')
df=df[['FIRST_NAME', 'LAST_NAME', 'BUSINESS_EMAIL',
       'PROGRAMMATIC_BUSINESS_EMAILS', 'PERSONAL_EMAIL', 'JOB_TITLE',
       'SENIORITY_LEVEL', 'DEPARTMENT', 'MOBILE_PHONE', 'DIRECT_NUMBER',
       'LINKEDIN_URL', 'PERSONAL_ADDRESS', 'PERSONAL_ADDRESS_2',
       'PERSONAL_CITY', 'PERSONAL_STATE', 'PERSONAL_ZIP', 'PERSONAL_ZIP4',
       'PROFESSIONAL_ADDRESS', 'PROFESSIONAL_ADDRESS_2', 'PROFESSIONAL_CITY',
       'PROFESSIONAL_STATE', 'PROFESSIONAL_ZIP', 'PROFESSIONAL_ZIP4',
       'COMPANY_NAME', 'COMPANY_DOMAIN', 'PRIMARY_INDUSTRY', 'COMPANY_SIC',
       'COMPANY_NAICS', 'COMPANY_ADDRESS', 'COMPANY_ADDRESS_2', 'COMPANY_CITY',
       'COMPANY_STATE', 'COMPANY_ZIP', 'COMPANY_ZIP4', 'COMPANY_LINKEDIN_URL',
       'COMPANY_REVENUE', 'COMPANY_EMPLOYEE_COUNT',
       'BUSINESS_EMAIL_VALIDATION_STATUS', 'BUSINESS_EMAIL_LAST_SEEN',
       'COMPANY_LAST_UPDATED', 'JOB_TITLE_LAST_UPDATED', 'LAST_UPDATED']]

In [4]:

columns_needed=df.columns.to_list()

In [13]:
sic_code = ["7311", "8721", "8748", "7319", "8742"]
target_industries = ["Advertising", "Media", "Marketing", "Consulting", "Tax Services", "Financial Services", "Wealth Plan"]

df_filtered = sic_target_industry_filter(df.copy(), sic_code, target_industries)
df_filtered.head()

,FIRST_NAME,LAST_NAME,BUSINESS_EMAIL,PROGRAMMATIC_BUSINESS_EMAILS,PERSONAL_EMAIL,JOB_TITLE,SENIORITY_LEVEL,DEPARTMENT,MOBILE_PHONE,DIRECT_NUMBER,...,COMPANY_ZIP,COMPANY_ZIP4,COMPANY_LINKEDIN_URL,COMPANY_REVENUE,COMPANY_EMPLOYEE_COUNT,BUSINESS_EMAIL_VALIDATION_STATUS,BUSINESS_EMAIL_LAST_SEEN,COMPANY_LAST_UPDATED,JOB_TITLE_LAST_UPDATED,LAST_UPDATED
81645,Morgen,Williams,mwilliams@yoursummit.com,"morgen.williams@yoursummit.com, morgen_william...",-,Group Benefits Account Manager,Manager,Sales,-,+13178465055,...,75240,6251,linkedin.com/company/summit-financial-group,100 Million to 250 Million,501 to 1000,Valid (Esp),2023-07-13T02:34:25.000Z,-,-,-
45328,Courtney,Donovan,cdonovan@cerespartners.com,"courtney.donovan@cerespartners.com, courtney_d...",-,Executive Assistant,Staff,Administrative,-,+15746757700,...,46617,-,linkedin.com/company/ceres-partners,10 Million to 25 Million,51 to 100,Valid (Esp),2023-09-24T18:31:12.000Z,2023-07-01T00:00:00.000Z,2023-07-01T00:00:00.000Z,2023-09-24T18:31:12.000Z
69685,Betsy,Graham,betsy@newleaffunding.com,"betsy.graham@newleaffunding.com, betsy_graham@...",missprissokstatern@outlook.com,Clinical Diabetes Educator,Staff,Health Services,-,-,...,33615,-,linkedin.com/company/new-leaf-funding,5 Million to 10 Million,26 to 50,-,-,-,-,-
37193,Jackson,Dillehay,jdillehay@pciawealth.com,"jackson.dillehay@pciawealth.com, jackson_dille...",-,Intern,Staff,Education,+16158789131,+12149049911,...,66211,-,linkedin.com/company/primecapitalinvestmentadv...,50 Million to 100 Million,251 to 500,-,-,2023-09-01T00:00:00.000Z,2023-09-01T00:00:00.000Z,-
46477,Terri,Allen,tallen@pciawealth.com,"terri.allen@pciawealth.com, terri_allen@pciawe...","crazybabe11014@swbell.net, dandtlewis@aol.com...",Board Member,Cxo,Executive,+18168387787,+19134916226,...,66211,-,linkedin.com/company/primecapitalinvestmentadv...,50 Million to 100 Million,251 to 500,-,-,-,-,-

In [15]:
#Check that atleat one sic_code is in each cell
df_filtered["COMPANY_SIC"].unique().tolist()
# len(df_filtered)

['0131;  6411;  7389;  8742',
 '0191;  7323;  8748',
 '0781;  6799;  8748',
 '0782;  6799;  8742',
 '1311;  8742',
 '1311;  8748',
 '1389;  8742',
 '1521;  6211;  8742',
 '1521;  6531;  8742',
 '1521;  8721',
 '1521;  8742',
 '1521;  8748',
 '1531;  5946;  8742',
 '1531;  6289;  8748',
 '1541;  6282;  8742',
 '1542;  6099;  8742',
 '1542;  6159;  8748',
 '1542;  7372;  8748',
 '1611;  7622;  8742',
 '1622;  8742',
 '1629;  6282;  8741;  8742',
 '1629;  8748',
 '1711;  6282;  8742',
 '1711;  6331;  8748',
 '1721;  7311;  8742',
 '1731;  5712;  7389;  8721',
 '1731;  6211;  6282;  8742',
 '1731;  6282;  8742',
 '1731;  7389;  8742',
 '1731;  8721',
 '1731;  8742',
 '1731;  8748',
 '1743;  8748',
 '1751;  7389;  8741;  8748',
 '1795;  8748',
 '2026;  6331;  8742',
 '2221;  8748',
 '2531;  8742',
 '2621;  5113;  6282;  8742',
 '2711;  4512;  8742',
 '2711;  6061;  6282;  8742',
 '2711;  8322;  8748',
 '2711;  8731;  8748',
 '2721;  6162;  8742',
 '2721;  6282;  8051;  8742',
 '2721;  8711;  8742',
 '2741;  7389;  8742',
 '2741;  8742',
 '2752;  6282;  8748',
 '2759;  6411;  8742',
 '2771;  8742',
 '2834;  8111;  8721',
 '2834;  8721',
 '2836;  6411;  8322;  8713;  8721',
 '2899;  8721',
 '3061;  6282;  8721',
 '3069;  6282;  8742',
 '3089;  6719;  8748',
 '3089;  8721',
 '3089;  8742',
 '3272;  8748',
 '3366;  8742',
 '3444;  6794;  7389;  8748',
 '3444;  8721',
 '3444;  8742',
 '3446;  6799;  8721',
 '3479;  8741;  8742',
 '3499;  5511;  6211;  8111;  8742',
 '3572;  6513;  8742',
 '3613;  7361;  8721',
 '3645;  6211;  8742',
 '3674;  7389;  8742',
 '3674;  8742',
 '3677;  5044;  8221;  8748',
 '3679;  8742;  8748',
 '3714;  6282;  8742',
 '3721;  8742',
 '3728;  6799;  8742',
 '3731;  6282;  8742',
 '3731;  6411;  8742',
 '3731;  8742',
 '3826;  6141;  8742',
 '3826;  6282;  8742',
 '3842;  5044;  8721',
 '3843;  8742',
 '3949;  8742',
 '4111;  4741;  8742',
 '4111;  8721',
 '4119;  6282;  7389;  8742',
 '4119;  7389;  8721',
 '4121;  6311;  6411;  8742',
 '4213;  8742',
 '4225;  6282;  8742',
 '4226;  8721',
 '4499;  6061;  6141;  8231;  8748',
 '4581;  6282;  8742',
 '4581;  8111;  8748',
 '4724;  8111;  8742',
 '4731;  6282;  8742',
 '4731;  8721',
 '4789;  6282;  8742',
 '4813;  6311;  8742',
 '4813;  7319',
 '4813;  8721',
 '4813;  8748',
 '4899;  7319',
 '4899;  8742',
 '4911;  8748',
 '4953;  5093;  8748',
 '5023;  6411;  8742',
 '5033;  6211;  6282;  7311',
 '5044;  8742',
 '5045;  6021;  8742',
 '5045;  6141;  8742',
 '5045;  7389;  8742',
 '5045;  8748',
 '5046;  8661;  8742',
 '5048;  5812;  7352;  8721',
 '5051;  6162;  7311',
 '5051;  8742;  8748',
 '5063;  6282;  8742',
 '5063;  7389;  8742',
 '5065;  8742',
 '5072;  6211;  6512;  6799;  7389;  8742',
 '5075;  8721',
 '5082;  6722;  8742',
 '5084;  6411;  8742;  8748',
 '5084;  7319',
 '5084;  8742',
 '5085;  8742',
 '5099;  8748',
 '5141;  8748',
 '5153;  6221;  8742',
 '5162;  6211;  6282;  8742',
 '5181;  6719;  8742',
 '5182;  6282;  8742',
 '5182;  8741;  8742',
 '5191;  6282;  8742',
 '5331;  8748',
 '5411;  6719;  8742',
 '5411;  8741;  8742',
 '5411;  8742',
 '5511;  6399;  8742',
 '5521;  6282;  8742',
 '5531;  7515;  8748',
 '5541;  6282;  8742',
 '5571;  8742;  8748',
 '5651;  8721',
 '5661;  5734;  8742',
 '5699;  5947;  6411;  8741;  8742',
 '5699;  8211;  8742',
 '5712;  8399;  8742',
 '5712;  8742',
 '5712;  8748',
 '5713;  6153;  8742',
 '5719;  7389;  8742',
 '5734;  8742',
 '5812;  6021;  6282;  8742',
 '5812;  6282;  8742',
 '5812;  8742',
 '5812;  8742;  8748',
 '5812;  8748',
 '5813;  6282;  8742',
 '5912;  8742',
 '5932;  8742',
 '5941;  6282;  8742',
 '5942;  8734;  8748',
 '5942;  8748',
 '5943;  8742',
 '5943;  8748',
 '5945;  6159;  8742',
 '5962;  6282;  8742',
 '5963;  8748',
 '5999;  8742',
 '6021;  6022;  6282;  8721',
 '6021;  6162;  6531;  7311',
 '6021;  6162;  8742',
 '6021;  6282;  8742',
 '6021;  6311;  8111;  8742',
 '6021;  7389;  8742',
 '6021;  8742',
 '6022;  6799;  8742',
 '6022;  8211;  8748',
 '6022;  8721',
 '6022;  8742',
 '6029;  8742',
 '6029;  8742;  8748',
 '6036;  8721',
 '6061;  6062;  7311',
 '6061;  6282;  8742',
 '6061;  7323;  8721',
 '6061;  8063;  8721',
 '6061;  8721',
 '6061;  8742',
 '6062;  8742',
 '6081;  8742',
 '6099;  6211;  8742',
 '6099;  6282;  8742',
 '6099;  6282;  8742;  8748',
 '6099;  7373;  8742',
 '6099;  8742',
 '6141;  6162;  8742',
 '6141;  6163;  8322;  8748',
 '6141;  6282;  7389;  8742',
 '6141;  6282;  8742',
 '6141;  6531;  8742',
 '6141;  7389;  8742',
 '6141;  8011;  8748',
 '6141;  8244;  8748',
 '6141;  8721',
 '6141;  8742',
 '6141;  8748',
 '6153;  6411;  8742',
 '6153;  7021;  8721',
 '6153;  7361;  8742',
 '6153;  7371;  8011;  8748',
 '6153;  7371;  8721',
 '6153;  7389;  8111;  8742',
 '6153;  7389;  8742',
 '6153;  8049;  8742',
 '6153;  8711;  8748',
 '6153;  8721',
 '6153;  8742',
 '6153;  8748',
 '6159;  6351;  8641;  8742',
 '6159;  7359;  8748',
 '6159;  7389;  8742',
 '6159;  7389;  8748',
 '6159;  8742',
 '6159;  8742;  8748',
 '6162;  6282;  8021;  8211;  8711;  8748',
 '6162;  7311',
 '6162;  7371;  8742',
 '6162;  8742',
 '6162;  8748',
 '6163;  6411;  8748',
 '6163;  8011;  8748',
 '6163;  8742',
 '6211;  6231;  8748',
 '6211;  6282;  6411;  8742',
 '6211;  6282;  8641;  8742',
 '6211;  6282;  8661;  8742;  8748',
 '6211;  6282;  8742',
 '6211;  6282;  8748',
 '6211;  6311;  8741;  8748',
 '6211;  6411;  7991;  8742',
 '6211;  6411;  8742',
 '6211;  6411;  8748',
 '6211;  6531;  8748',
 '6211;  6719;  8748',
 '6211;  6726;  7389;  8742',
 '6211;  6799;  8742',
 '6211;  7319',
 '6211;  7322;  8742',
 '6211;  7361;  8748',
 '6211;  7389;  8742',
 '6211;  7389;  8748',
 '6211;  7929;  8748',
 '6211;  8062;  8742',
 '6211;  8221;  8742',
 '6211;  8661;  8742',
 '6211;  8721',
 '6211;  8742',
 '6211;  8742;  8748',
 '6211;  8748',
 '6221;  8748',
 '6231;  8742',
 '6282;  6311;  7389;  8742',
 '6282;  6311;  8742',
 '6282;  6321;  8742',
 '6282;  6324;  8742',
 '6282;  6331;  8742',
 '6282;  6371;  8742',
 '6282;  6411;  8051;  8742',
 '6282;  6411;  8399;  8742',
 '6282;  6411;  8742',
 '6282;  6411;  8748',
 '6282;  6512;  8742',
 '6282;  6513;  8742',
 '6282;  6531;  7299;  8742',
 '6282;  6531;  8742',
 '6282;  6722;  8721',
 '6282;  6726;  8742',
 '6282;  6798;  8742',
 '6282;  6799;  8243;  8742',
 '6282;  6799;  8742',
 '6282;  7291;  8721',
 '6282;  7299;  8062;  8742',
 '6282;  7311',
 '6282;  7319',
 '6282;  7371;  7389;  8721',
 '6282;  7371;  8111;  8721',
 '6282;  7371;  8742',
 '6282;  7371;  8748',
 '6282;  7381;  8742',
 '6282;  7389;  8721',
 '6282;  7389;  8742',
 '6282;  7389;  8748',
 '6282;  8111;  8742',
 '6282;  8211;  8742',
 '6282;  8211;  8748',
 '6282;  8351;  8742',
 '6282;  8621;  8742',
 '6282;  8661;  8742',
 '6282;  8699;  8742',
 '6282;  8721',
 '6282;  8721;  8742',
 '6282;  8721;  8748',
 '6282;  8741;  8742',
 '6282;  8742',
 '6282;  8742;  8748',
 '6282;  8748',
 '6289;  8721;  8748',
 '6311;  6331;  8742',
 '6311;  6411;  8742',
 '6311;  8742',
 '6311;  8742;  8748',
 '6311;  8748',
 '6331;  6411;  8721',
 '6331;  7389;  8742',
 '6331;  8721',
 '6331;  8742',
 '6331;  8742;  8748',
 '6351;  8721',
 '6361;  6531;  8748',
 '6371;  6733;  8742',
 '6371;  8721',
 '6371;  8742',
 '6411;  6531;  8742',
 '6411;  7336;  7374;  8721',
 '6411;  7371;  8742',
 '6411;  7389;  8721',
 '6411;  7389;  8741;  8742',
 '6411;  7389;  8742',
 '6411;  8011;  8742',
 '6411;  8111;  8742',
 '6411;  8399;  8712;  8742',
 '6411;  8721',
 '6411;  8721;  8742',
 '6411;  8721;  8748',
 '6411;  8742',
 '6411;  8748',
 '6512;  8742',
 '6512;  8742;  8748',
 '6512;  8748',
 '6513;  7521;  8742',
 '6519;  8699;  8748',
 '6531;  6552;  8748',
 '6531;  8721',
 '6531;  8741;  8742',
 '6531;  8742',
 '6531;  8748',
 '6552;  6799;  8742',
 '6552;  8742',
 '6552;  8748',
 '6719;  7389;  8742',
 '6719;  8742',
 '6719;  8743;  8748',
 '6722;  6799;  8742',
 '6722;  8399;  8742',
 '6722;  8742',
 '6722;  8748',
 '6726;  7389;  8748',
 '6733;  8741;  8742',
 '6733;  8742',
 '6733;  8748',
 '6794;  8661;  8748',
 '6799;  7311',
 '6799;  7319',
 '6799;  7389;  8721',
 '6799;  7389;  8742',
 '6799;  7549;  8742',
 '6799;  8062;  8399;  8748',
 '6799;  8713;  8721',
 '6799;  8741;  8742',
 '6799;  8741;  8748',
 '6799;  8742',
 '6799;  8748',
 '7011;  8721',
 '7011;  8742',
 '7231;  8721',
 '7291;  7389;  8721',
 '7291;  8721',
 '7291;  8721;  8742',
 '7291;  8742',
 '7299;  7322;  8742',
 '7299;  7359;  8742',
 '7299;  7361;  7389;  8742',
 '7299;  8711;  8748',
 '7299;  8721',
 '7299;  8742',
 '7299;  8748',
 '7311',
 '7311;  7319',
 '7311;  8742',
 '7319',
 '7319;  8713;  8742',
 '7322;  7389;  8721',
 '7322;  7389;  8742',
 '7322;  8721',
 '7322;  8742',
 '7322;  8742;  8748',
 '7322;  8748',
 '7323;  7389;  8742',
 '7323;  8721;  8748',
 '7323;  8742',
 '7342;  8742',
 '7359;  8721',
 '7359;  8742',
 '7361;  8713;  8721',
 '7361;  8721',
 '7361;  8742',
 '7361;  8748',
 '7363;  8721',
 '7371;  7379;  8748',
 '7371;  8111;  8742',
 '7371;  8721',
 '7371;  8742',
 '7371;  8742;  8748',
 '7371;  8748',
 '7372;  7389;  8721',
 '7372;  8721',
 '7372;  8721;  8742',
 '7372;  8741;  8742',
 '7372;  8742',
 '7373;  7389;  8742',
 '7374;  8742',
 '7375;  8111;  8748',
 '7375;  8742',
 '7375;  8748',
 '7379;  8062;  8742;  8748',
 '7379;  8741;  8742',
 '7379;  8742',
 '7379;  8748',
 '7381;  8748',
 '7389;  8011;  8742',
 '7389;  8021;  8748',
 '7389;  8231;  8742',
 '7389;  8611;  8742',
 '7389;  8641;  8742',
 '7389;  8661;  8748',
 '7389;  8721',
 '7389;  8721;  8742',
 '7389;  8733;  8742',
 '7389;  8741;  8742',
 '7389;  8742',
 '7389;  8742;  8748',
 '7389;  8748',
 '7538;  8742',
 '7699;  8721',
 '7812;  8011;  8742',
 '7941;  8069;  8742',
 '7992;  8748',
 '7999;  8742',
 '8011;  8742',
 '8041;  8742',
 '8042;  8742',
 '8043;  8721',
 '8049;  8742',
 '8093;  8742',
 '8099;  8222;  8742;  8748',
 '8099;  8748',
 '8111;  8721',
 '8111;  8721;  8742',
 '8111;  8742',
 '8211;  8713;  8721',
 '8211;  8713;  8742',
 '8211;  8721',
 '8211;  8742',
 '8221;  8742',
 '8231;  8742',
 '8249;  8742',
 '8299;  8748',
 '8322;  8742',
 '8322;  8748',
 '8611;  8621;  8748',
 '8611;  8742',
 '8611;  8742;  8748',
 '8621;  8721',
 '8621;  8742',
 '8641;  8742',
 '8661;  8742',
 '8661;  8748',
 '8699;  8711;  8748',
 '8699;  8721',
 '8711;  8732;  8742',
 '8711;  8742',
 '8712;  8742',
 '8713;  8721',
 '8713;  8748',
 '8721',
 '8721;  8742',
 '8721;  8748',
 '8732;  8741;  8742',
 '8732;  8742',
 '8732;  8748',
 '8733;  8748',
 '8734;  8748',
 '8741;  8742',
 '8741;  8742;  8748',
 '8741;  8748',
 '8742',
 '8742;  8748',
 '8748',
 '2721;  7311;  9531',
 '3841;  7319;  7322',
 '4225;  7319;  7322',
 '5013;  7319;  7322',
 '5045;  7311;  8743',
 '5099;  5199;  7221;  7319;  8742;  8811',
 '5141;  7311;  7389',
 '5963;  7319;  7322',
 '6282;  7319;  7389',
 '6282;  8711;  8742;  9311',
 '6282;  8721;  8741',
 '6282;  8742;  8999',
 '6411;  8748;  8999',
 '6531;  7319;  7322',
 '6531;  7319;  7322;  8111',
 '7231;  7375;  8742;  9111',
 '7311;  7371;  7372',
 '7311;  7389',
 '7311;  7513',
 '7311;  7991;  8063',
 '7311;  8211',
 '7319;  7322',
 '7319;  7322;  7371',
 '7319;  7322;  8211;  8711',
 '7319;  7322;  8641',
 '7319;  7389',
 '7319;  8221;  8741',
 '7389;  8748;  9111',
 '8322;  8721;  8741',
 '8699;  8748;  8999',
 '8721;  8741',
 '8721;  8743',
 '8742;  8743',
 '8742;  8748;  9111',
 '8742;  8811',
 '8742;  8999',
 '8742;  9224',
 '8742;  9411',
 '8748;  8999',
 '8748;  9224',
 '8748;  9531']

In [6]:
#filter by seniority   
campaign_data=filter_by_seniority(df_filtered, ["staff"])

campaign_data.SENIORITY_LEVEL.unique()

array(['Cxo', 'Manager', 'Vp', 'Director'], dtype=object)

In [7]:
#campaign_data["SENIORITY_LEVEL"].value_counts()
campaign_data["BUSINESS_EMAIL_VALIDATION_STATUS"].unique().tolist()

['-', 'Valid (Esp)', 'Valid (Digital)']

## Task1: Creation of Email Maketing list

In [8]:
def filter_by_valid_business_email(df, column_name="BUSINESS_EMAIL_VALIDATION_STATUS"):
  """
  Filters a dataframe for rows with "Valid" in the BUSINESS_EMAIL_VALIDATION_STATUS column.

  Args:
    df: The dataframe to filter.
    column_name: The name of the column containing validation status.

  Returns:
    A new dataframe containing only rows with validated emails.
  """
  return df[df[column_name].str.contains("Valid", case=False)]

Email_Funnel_Campaign_List=filter_by_valid_business_email(campaign_data, column_name="BUSINESS_EMAIL_VALIDATION_STATUS").reset_index()[columns_needed]

In [9]:
Email_Funnel_Campaign_List.head()

,FIRST_NAME,LAST_NAME,BUSINESS_EMAIL,PROGRAMMATIC_BUSINESS_EMAILS,PERSONAL_EMAIL,JOB_TITLE,SENIORITY_LEVEL,DEPARTMENT,MOBILE_PHONE,DIRECT_NUMBER,...,COMPANY_ZIP,COMPANY_ZIP4,COMPANY_LINKEDIN_URL,COMPANY_REVENUE,COMPANY_EMPLOYEE_COUNT,BUSINESS_EMAIL_VALIDATION_STATUS,BUSINESS_EMAIL_LAST_SEEN,COMPANY_LAST_UPDATED,JOB_TITLE_LAST_UPDATED,LAST_UPDATED
0,Chad,Sluss,csluss@nefassociation.org,"chad.sluss@nefassociation.org, chad_sluss@nefa...",-,Chief Executive Officer,Cxo,Executive,+16162049599,+16164582464,...,60065,-,linkedin.com/company/national-equipment-financ...,5 Million to 10 Million,26 to 50,Valid (Esp),2023-08-27T06:58:25.000Z,2023-06-01T00:00:00.000Z,2023-06-01T00:00:00.000Z,2023-08-27T06:58:25.000Z
1,Event,Shop,billy.mcentee@mediafinancial.com,"event.shop@mediafinancial.com, event_shop@medi...",-,Owner,Cxo,Executive,+15618763528,-,...,33401,-,-,1 Million to 5 Million,11 to 25,Valid (Esp),2023-10-01T07:00:00.000Z,2023-07-01T00:00:00.000Z,2023-07-01T00:00:00.000Z,2023-10-01T07:00:00.000Z
2,Tony,Jaynes,tony.jaynes@wegnercpas.com,"tony.jaynes@wegnercpas.com, tony_jaynes@wegner...","tntjaynes@centurytel.net, jinwood@yahoo.com, ...",Property Manager,Manager,Executive,-,+17025971969,...,53713,-,linkedin.com/company/wegnercpas,100 Million to 250 Million,501 to 1000,Valid (Esp),2023-08-09T03:55:58.000Z,2023-08-01T00:00:00.000Z,2023-08-01T00:00:00.000Z,2023-08-09T03:55:58.000Z
3,Patrick,Estioko,pestioko@frankrimerman.com,"patrick.estioko@frankrimerman.com, patrick_est...",patrickestioko@hotmail.com,Information Technology Network Manager,Manager,Information Technology,-,+14154392007,...,94304,-,linkedin.com/company/frank-rimerman---co--llp,250 Million to 500 Million,1001 to 5000,Valid (Esp),2023-03-20T18:57:13.000Z,2023-08-01T00:00:00.000Z,2023-08-01T00:00:00.000Z,2023-08-01T00:00:00.000Z
4,Jeffrey,Filter,jeff.filter@wegnercpas.com,"jeffrey.filter@wegnercpas.com, jeffrey_filter@...",-,Partner,Cxo,Executive,-,+16085246450,...,53713,-,linkedin.com/company/wegnercpas,100 Million to 250 Million,501 to 1000,Valid (Esp),2023-07-26T12:27:08.000Z,2023-09-01T00:00:00.000Z,2023-09-01T00:00:00.000Z,2023-09-01T00:00:00.000Z

In [10]:
#Check if the result is correct
Email_Funnel_Campaign_List["BUSINESS_EMAIL_VALIDATION_STATUS"].unique().tolist()

['Valid (Esp)', 'Valid (Digital)']

In [11]:
Email_Funnel_Campaign_List['JOB_TITLE'].value_counts()

Managing Director                    24
Owner                                20
Manager                              17
President                            15
Principal                            15
                                     ..
Manager, Collections Analytics        1
Manager Partner Success               1
Senior Director Of Public Affairs     1
Board Of Director                     1
Portfolio Group And Partner           1
Name: JOB_TITLE, Length: 320, dtype: int64

## Task 2:  Filter for Conversation Ai List

In [12]:
#Write a function to filter phone number

def enrich_phone_numbers(df):
    """
    Enriches phone numbers by replacing "-" with NaN, checking for the column with the lowest number of NaNs,
    and filling missing values based on the corresponding value in the column with more NaNs.

    Args:
        df: The pandas dataframe with phone number columns.

    Returns:
        A new dataframe with an enriched "ENRICHED_PHONE_NUMBER" column, with rows containing NaNs dropped.
    """
    phone_columns = ["MOBILE_PHONE", "DIRECT_NUMBER"]

    # Make a copy of the DataFrame to avoid modifying the original
    df = df.copy()

    # Replace "-" with NaN in the phone number columns
    df[phone_columns] = df[phone_columns].replace('-', np.nan)

    # Count the number of NaNs in each phone column
    na_counts = df[phone_columns].isna().sum()

    # Find the column with the lowest number of NaNs
    lowest_na_column = na_counts.idxmin()

    # Find the column with the highest number of NaNs
    highest_na_column = na_counts.idxmax()

    # Create a new "ENRICHED_PHONE_NUMBER" column and fill with entries from the lowest NA column
    df["ENRICHED_PHONE_NUMBER"] = df[lowest_na_column]

    # Fill missing values with valid entries from the highest NA column (if available)
    mask = df["ENRICHED_PHONE_NUMBER"].isna() & ~df[highest_na_column].isna()
    df.loc[mask, "ENRICHED_PHONE_NUMBER"] = df.loc[mask, highest_na_column]

    # Drop rows with missing values in the "ENRICHED_PHONE_NUMBER" column
    df.dropna(subset=["ENRICHED_PHONE_NUMBER"], inplace=True)

    return df

# Apply the function to the DataFrame and store the result in enriched_df
enriched_df = enrich_phone_numbers(campaign_data)

In [13]:
# Create a function to sort the data by "JOB_TYPE" and filter out rows where "JOB_TYPE" contains certain keywords such as "intern," "professor," "scientist," "engineer," "mechanical," and "mechanics." 

def sort_and_filter_jobs(df, keywords_to_exclude):
    """
    Sorts the data by JOB_TITLEand filters out rows with specific keywords in JOB_TITLE.

    Args:
        df: The pandas dataframe containing the job data.

    Returns:
        A new dataframe sorted by JOB_TITLE and filtered based on specified keywords.
    """
    
    # Sort the data by JOB_TYPE
    sorted_df = df.sort_values(by="JOB_TITLE")

    # Filter out rows with JOB_TITLE containing the specified keywords
    filtered_df = sorted_df[~sorted_df["JOB_TITLE"].str.lower().str.contains('|'.join(keywords_to_exclude))]

    return filtered_df

# Print the result
keywords_to_exclude = ["intern", "professor", "scientist", "engineer", "mechanical", "mechanics"]
Conversation_AI_List=sort_and_filter_jobs(enriched_df,keywords_to_exclude).reset_index()[["FIRST_NAME", "LAST_NAME","MOBILE_PHONE","DIRECT_NUMBER", "ENRICHED_PHONE_NUMBER"]]
Conversation_AI_List.head(20)

   FIRST_NAME    LAST_NAME  MOBILE_PHONE DIRECT_NUMBER ENRICHED_PHONE_NUMBER
0      Callie       Spivey           NaN  +13125684200          +13125684200
1      Susana        Perez  +15129644812  +15122570340          +15122570340
2      Thomas     Phillips  +18646803812  +18643081218          +18643081218
3       Tracy     Daddario           NaN  +17815848019          +17815848019
4     Carolyn  Chamberlain  +13865460807  +12399859303          +12399859303
5       Shawn    Pellacani  +16504507810  +16504507810          +16504507810
6     Jessica     Erickson           NaN  +12122073427          +12122073427
7        Anne         Hill           NaN  +13037227776          +13037227776
8     Kaleigh         Rowe  +13176946938           NaN          +13176946938
9         Bev     Laughlin  +16419190326  +16416933037          +16416933037
10       Reen     Williams           NaN  +18043209515          +18043209515
11    Jessica         Hull           NaN  +18585235500          +18585235500
12      Ellie       Tucker  +13363570797  +15753473400          +15753473400
13     Miguel        Ceron  +16193583959  +16122154333          +16122154333
14    Quintin         King           NaN  +18008499791          +18008499791
15       Adam        Hymer           NaN  +16158723000          +16158723000
16     Joshua       Ziegel           NaN  +18589256279          +18589256279
17      Diane       Pierce  +17049050216  +19784961177          +19784961177
18     Reuben      Harness  +18593240018  +15854211011          +15854211011
19      Megan       Jacoby           NaN  +17039930072          +17039930072

## Task3: Social Media Campaign List

 * Create a function that takes a DataFrame and returns a new DataFrame containing only rows with valid 'PERSONAL_EMAIL' addresses for all job types:

In [14]:
def filter_valid_personal_emails(df):
    """
    Filters a DataFrame to include only rows with valid 'PERSONAL_EMAIL' addresses for all job types.

    Args:
        df: The pandas DataFrame containing 'JOB_TYPE' and 'PERSONAL_EMAIL' columns.

    Returns:
        A new DataFrame with rows containing valid 'PERSONAL_EMAIL' addresses for all job types.
    """
    # Filter rows with valid 'PERSONAL_EMAIL'
    valid_email_df = df[df['PERSONAL_EMAIL'].str.contains('@', na=False)]

    return valid_email_df

#Apply the function on df_filtered 
Social_Media_Mampaign_list=filter_valid_personal_emails(df_filtered).reset_index()[columns_needed]

In [15]:
Social_Media_Mampaign_list["SENIORITY_LEVEL"].value_counts()

Staff       859
Manager     342
Cxo         321
Vp          109
Director    108
-            41
Name: SENIORITY_LEVEL, dtype: int64

## Combine all the Campaign List into a single excel workbook

In [16]:

#Combine all files into single workbook

def df_to_excel_openpyxl(dfs, file_path, sheet_names=None):
    """
    Combines multiple pandas dataframes into a single Excel file with different sheets, 
    adding the number of rows to each sheet name.

    Args:
        dfs: A list of pandas dataframes to write.
        file_path: The path to save the file.
        sheet_names: A list of names for the sheets (optional, defaults to DataFrame titles).

    Returns:
        None
    """
    wb = Workbook()

    for df, name in zip(dfs, sheet_names):
        sheet_name = f"{name}_{len(df)}"
        ws = wb.create_sheet(sheet_name)
        ws.append(df.columns.tolist())
        for row in df.values:
            ws.append(row.tolist())

    wb.save(file_path)
# Apply the function
# dfs=[Email_Funnel_Campaign_List, Conversation_AI_List, Social_Media_Mampaign_list]
# sheet_names=["Email_Funnel_Campaign_List", "Conversation_AI_List", "Social_Media_Mampaign_list"]
# df_to_excel_openpyxl(dfs, "Traffic-Convert_Campaign_data.xlsx", sheet_names)

# Second campagn list Task

1. states must be US states len(2)
2. take address from personal, professional, and business Address, must not be P.O.Box

second task
1. industry list=[advert, media, intertainment, PR, Events, Printing, marketing,publishing, broadcast]
2. sic code 7311
3. address

In [3]:
#read data using get_data function
first_list=get_data("./raw_data/Adgency-7311_SecondPriority.csv")
target_industries=['Advertising Services', 'Marketing','Book And Periodical Publishing', 'Entertainment Providers', 'Events Services','Broadcast Media Production And Distribution','Public Relations And Communications Services', 'Online Audio And Video Media', 'Printing Services','Newspaper Publishing', 'Newspapers']

In [4]:
#Get saze of data
first_list.shape

(100000, 42)

In [5]:
#get columns names
first_list.columns

Index(['FIRST_NAME', 'LAST_NAME', 'BUSINESS_EMAIL',
       'PROGRAMMATIC_BUSINESS_EMAILS', 'PERSONAL_EMAIL', 'JOB_TITLE',
       'SENIORITY_LEVEL', 'DEPARTMENT', 'MOBILE_PHONE', 'DIRECT_NUMBER',
       'LINKEDIN_URL', 'PERSONAL_ADDRESS', 'PERSONAL_ADDRESS_2',
       'PERSONAL_CITY', 'PERSONAL_STATE', 'PERSONAL_ZIP', 'PERSONAL_ZIP4',
       'PROFESSIONAL_ADDRESS', 'PROFESSIONAL_ADDRESS_2', 'PROFESSIONAL_CITY',
       'PROFESSIONAL_STATE', 'PROFESSIONAL_ZIP', 'PROFESSIONAL_ZIP4',
       'COMPANY_NAME', 'COMPANY_DOMAIN', 'PRIMARY_INDUSTRY', 'COMPANY_SIC',
       'COMPANY_NAICS', 'COMPANY_ADDRESS', 'COMPANY_ADDRESS_2', 'COMPANY_CITY',
       'COMPANY_STATE', 'COMPANY_ZIP', 'COMPANY_ZIP4', 'COMPANY_LINKEDIN_URL',
       'COMPANY_REVENUE', 'COMPANY_EMPLOYEE_COUNT',
       'BUSINESS_EMAIL_VALIDATION_STATUS', 'BUSINESS_EMAIL_LAST_SEEN',
       'COMPANY_LAST_UPDATED', 'JOB_TITLE_LAST_UPDATED', 'LAST_UPDATED'],
      dtype='object')

In [5]:
#filter for USA states only
state_df=filter_usa_states(first_list)

In [7]:
state_df.shape

(71239, 42)

In [6]:
#filter for valid address
valid_address_df=filter_and_label_valid_addresses(state_df.copy())

In [10]:
valid_address_df [['PERSONAL_ADDRESS', 'PERSONAL_ADDRESS_2',
        'PROFESSIONAL_ADDRESS', 'PROFESSIONAL_ADDRESS_2',
        'COMPANY_ADDRESS', 'COMPANY_ADDRESS_2','VALID_ADDRESS', 'ADDRESS_USED']].head(20)

,PERSONAL_ADDRESS,PERSONAL_ADDRESS_2,PROFESSIONAL_ADDRESS,PROFESSIONAL_ADDRESS_2,COMPANY_ADDRESS,COMPANY_ADDRESS_2,VALID_ADDRESS,ADDRESS_USED
0,3410 Galt Ocean Dr,Apt 1005n,-,-,8720 Georgia Ave,-,3410 Galt Ocean Dr,PERSONAL_ADDRESS
2,-,-,-,-,444 W Ocean Blvd Ste 150,-,444 W Ocean Blvd Ste 150,COMPANY_ADDRESS
5,-,-,7202 Whitmore Lk Rd,-,7711 Bonhomme Ave,-,7202 Whitmore Lk Rd,PROFESSIONAL_ADDRESS
7,23 N Cir Dr Apt W11,-,-,-,1261 E Dyer Rd,-,23 N Cir Dr Apt W11,PERSONAL_ADDRESS
9,-,-,233 S Wacker Dr,Ste 3330,233 South Wacker Dr,Suite 3500,233 S Wacker Dr,PROFESSIONAL_ADDRESS
12,-,-,-,-,250 Nw Richards Rd,-,250 Nw Richards Rd,COMPANY_ADDRESS
13,8521 Pepperdine Dr,-,-,-,224 Nw 13th Ave,-,8521 Pepperdine Dr,PERSONAL_ADDRESS
14,-,-,1000 Louis Rose Pl,-,1101 Red Ventures Dr,-,1000 Louis Rose Pl,PROFESSIONAL_ADDRESS
15,-,-,35 West Wacker Dr,-,35 West Wacker Dr,-,35 West Wacker Dr,PROFESSIONAL_ADDRESS
16,4320 Hwy 365,-,-,-,1642 Wilcox Ave,-,4320 Hwy 365,PERSONAL_ADDRESS
17,26 Mdw Rd,-,909 3rd Ave,-,909 Third Ave,-,26 Mdw Rd,PERSONAL_ADDRESS
18,-,-,601 Edgewater Dr,Ste 250,6021 Connection Dr,-,601 Edgewater Dr,PROFESSIONAL_ADDRESS
19,-,-,-,-,90 Merrick Ave Ste 530,-,90 Merrick Ave Ste 530,COMPANY_ADDRESS
20,-,-,980 Hammond Dr,Ste 1000,1101 Red Ventures Dr,-,980 Hammond Dr,PROFESSIONAL_ADDRESS
21,-,-,55 Cambridge St,Ste 200,6908 Hollywood Blvd,-,55 Cambridge St,PROFESSIONAL_ADDRESS
22,147 Prospect Ave,-,-,-,500 3rd St N,-,147 Prospect Ave,PERSONAL_ADDRESS
24,8611 Concord Mls Blvd Ste 201,-,1350 Pennsylvania Ave Nw,-,1 Leadership Pl,-,8611 Concord Mls Blvd Ste 201,PERSONAL_ADDRESS
25,360 Stratford Ln,-,-,-,90 Southwark St,-,360 Stratford Ln,PERSONAL_ADDRESS
26,-,-,2323 Broadway,-,2323 Broadway,-,2323 Broadway,PROFESSIONAL_ADDRESS
27,-,-,1675 Broadway,-,1675 Broadway,-,1675 Broadway,PROFESSIONAL_ADDRESS

In [11]:
valid_address_df.shape

(69176, 44)

In [11]:
#save to file
save_df_to_csv(valid_address_df,'first_priority_valid_address_list')

DataFrame successfully saved to Output_list_DataBase\first_priority_valid_address_list.csv

In [7]:
valid_numbers=enrich_phone_numbers(valid_address_df.copy())

In [13]:
#check the number 
valid_numbers.shape

(48567, 45)

In [8]:
#filter for valid business number enriched with personal number for non-validated business emails
valid_number_email_df=filter_by_valid_business_personal_email(valid_numbers,
                                                           validation_column = "BUSINESS_EMAIL_VALIDATION_STATUS",
                                                           business_email_column= "BUSINESS_EMAIL",
                                                           personal_email_column = "PERSONAL_EMAIL")

In [14]:
valid_number_email_df.columns

Index(['FIRST_NAME', 'LAST_NAME', 'BUSINESS_EMAIL',
       'PROGRAMMATIC_BUSINESS_EMAILS', 'PERSONAL_EMAIL', 'JOB_TITLE',
       'SENIORITY_LEVEL', 'DEPARTMENT', 'MOBILE_PHONE', 'DIRECT_NUMBER',
       'LINKEDIN_URL', 'PERSONAL_ADDRESS', 'PERSONAL_ADDRESS_2',
       'PERSONAL_CITY', 'PERSONAL_STATE', 'PERSONAL_ZIP', 'PERSONAL_ZIP4',
       'PROFESSIONAL_ADDRESS', 'PROFESSIONAL_ADDRESS_2', 'PROFESSIONAL_CITY',
       'PROFESSIONAL_STATE', 'PROFESSIONAL_ZIP', 'PROFESSIONAL_ZIP4',
       'COMPANY_NAME', 'COMPANY_DOMAIN', 'PRIMARY_INDUSTRY', 'COMPANY_SIC',
       'COMPANY_NAICS', 'COMPANY_ADDRESS', 'COMPANY_ADDRESS_2', 'COMPANY_CITY',
       'COMPANY_STATE', 'COMPANY_ZIP', 'COMPANY_ZIP4', 'COMPANY_LINKEDIN_URL',
       'COMPANY_REVENUE', 'COMPANY_EMPLOYEE_COUNT',
       'BUSINESS_EMAIL_VALIDATION_STATUS', 'BUSINESS_EMAIL_LAST_SEEN',
       'COMPANY_LAST_UPDATED', 'JOB_TITLE_LAST_UPDATED', 'LAST_UPDATED',
       'VALID_ADDRESS', 'ADDRESS_USED', 'ENRICHED_PHONE_NUMBER',
       'Valid_Business_Email'],
      dtype='object')

In [9]:
df_progra_emails=split_columns_by_separator(valid_number_email_df, 'PROGRAMMATIC_BUSINESS_EMAILS', separator=',',keep_non_missing_only=True,drop_duplicates=True)
df_progra_emails.columns

Index(['FIRST_NAME', 'LAST_NAME', 'BUSINESS_EMAIL',
       'PROGRAMMATIC_BUSINESS_EMAILS', 'PERSONAL_EMAIL', 'JOB_TITLE',
       'SENIORITY_LEVEL', 'DEPARTMENT', 'MOBILE_PHONE', 'DIRECT_NUMBER',
       'LINKEDIN_URL', 'PERSONAL_ADDRESS', 'PERSONAL_ADDRESS_2',
       'PERSONAL_CITY', 'PERSONAL_STATE', 'PERSONAL_ZIP', 'PERSONAL_ZIP4',
       'PROFESSIONAL_ADDRESS', 'PROFESSIONAL_ADDRESS_2', 'PROFESSIONAL_CITY',
       'PROFESSIONAL_STATE', 'PROFESSIONAL_ZIP', 'PROFESSIONAL_ZIP4',
       'COMPANY_NAME', 'COMPANY_DOMAIN', 'PRIMARY_INDUSTRY', 'COMPANY_SIC',
       'COMPANY_NAICS', 'COMPANY_ADDRESS', 'COMPANY_ADDRESS_2', 'COMPANY_CITY',
       'COMPANY_STATE', 'COMPANY_ZIP', 'COMPANY_ZIP4', 'COMPANY_LINKEDIN_URL',
       'COMPANY_REVENUE', 'COMPANY_EMPLOYEE_COUNT',
       'BUSINESS_EMAIL_VALIDATION_STATUS', 'BUSINESS_EMAIL_LAST_SEEN',
       'COMPANY_LAST_UPDATED', 'JOB_TITLE_LAST_UPDATED', 'LAST_UPDATED',
       'VALID_ADDRESS', 'ADDRESS_USED', 'ENRICHED_PHONE_NUMBER',
       'Valid_Business_Email', 'PROGRAMMATIC_BUSINESS_EMAILS_1',
       'PROGRAMMATIC_BUSINESS_EMAILS_2', 'PROGRAMMATIC_BUSINESS_EMAILS_3',
       'PROGRAMMATIC_BUSINESS_EMAILS_4', 'PROGRAMMATIC_BUSINESS_EMAILS_5',
       'PROGRAMMATIC_BUSINESS_EMAILS_6', 'PROGRAMMATIC_BUSINESS_EMAILS_7',
       'PROGRAMMATIC_BUSINESS_EMAILS_8', 'PROGRAMMATIC_BUSINESS_EMAILS_9',
       'PROGRAMMATIC_BUSINESS_EMAILS_10', 'PROGRAMMATIC_BUSINESS_EMAILS_11',
       'PROGRAMMATIC_BUSINESS_EMAILS_12', 'PROGRAMMATIC_BUSINESS_EMAILS_13',
       'PROGRAMMATIC_BUSINESS_EMAILS_14', 'PROGRAMMATIC_BUSINESS_EMAILS_15',
       'PROGRAMMATIC_BUSINESS_EMAILS_16', 'PROGRAMMATIC_BUSINESS_EMAILS_17'],
      dtype='object')

In [10]:
# Example usage:
# Assume 'data' is your original DataFrame loaded with necessary columns
# selected_columns = { ... } # Define your column mapping as provided earlier
formatted_df = liveramp_formatter(df_progra_emails)
formatted_df

,Client Customer ID,First Name,Last Name,Street Address 1,Street Address 2,City,State,Zip Code,Zip Code Plus 4,Email1,Email2,Email3,PhoneNumber1,PhoneNumber2
0,7253,Nhora,Murphy,3410 Galt Ocean Dr,-,Fort Lauderdale,FL,33308,-,nmurphy@tmncorp.com,nhora.murphy@tmncorp.com,nhora_murphy@tmncorp.com,+13014680956,NaN
5,7706,Mary,Mccauley,7202 Whitmore Lk Rd,NaN,Brighton,MI,-,-,-,mary.mccauley@brightonagency.com,mary_mccauley@brightonagency.com,+13139782253,NaN
7,2969,Junia,Bauer,23 N Cir Dr Apt W11,-,Colorado Springs,CO,80909,6368,craig.buell@yahoo.com,junia.bauer@hobbsherder.com,junia_bauer@hobbsherder.com,+12033562496,+17209994687
13,1584,Keith,Kan,8521 Pepperdine Dr,-,Vienna,VA,22180,7047,asideat52@yahoo.com,keith.kan@wk.com,keith_kan@wk.com,+17035735754,NaN
16,9068,Angela,Strain,4320 Hwy 365,-,Port Arthur,TX,77642,7516,star_to_star2001@yahoo.co.in,angela.strain@colliersimon.com,angela_strain@colliersimon.com,+14097242203,+19012735641
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99990,9126,Bonnie,Overton,11000 Regency Pkwy,NaN,Raleigh,NC,-,-,saphire0777@gmail.com,bonnie.overton@evokegroup.com,bonnie_overton@evokegroup.com,+19194630330,NaN
99991,9059,Emily,Hean,555 Market St,NaN,-,CA,-,-,emily.hean@rapp.com,emily.hean@rapp.com,emily_hean@rapp.com,+15033481744,NaN
99993,9909,Monica,Leedom,8671 Cord St Ne,3250 Rice St,Circle Pines,MN,55014,-,mleedom@mngamingservices.com,monica.leedom@mngamingservices.com,monica_leedom@mngamingservices.com,+16516384638,+16513076267
99995,5143,Kate,Brochu,345 Hudson St,-,-,NY,-,-,-,kate.brochu@everydayhealth.com,kate_brochu@everydayhealth.com,+15182659117,NaN
99997,9293,Caroline,Kenne,4299 Webster Dr,-,York,PA,17402,3332,alexandriagrey@comcast.net,caroline.kenne@karmaagency.com,caroline_kenne@karmaagency.com,+16172049500,+17175720473

In [11]:
count_duplicates(formatted_df)
formatted_df.shape

(48567, 14)

In [12]:
#Save to file
save_df_to_csv(formatted_df,"email_number_liveramp_list1")

DataFrame successfully saved to Output_list_DataBase\email_number_liveramp_list1.csv

In [ ]:
def liveramp_adlist(file_path, adlist_name, **kwargs):
    df=get_data(file_path, adlist_name, **kwargs)

# Second Priority List

In [5]:
target_industries=['Advertising Services', 'Animation And Post-Production','Writing And Editing', 'Fundraising','Spectator Sports','Movies, Videos, And Sound','Marketing','Book And Periodical Publishing', 'Entertainment Providers', 'Events Services','Broadcast Media Production And Distribution','Public Relations And Communications Services', 'Online Audio And Video Media', 'Printing Services','Newspaper Publishing', 'Newspapers', 'Sports', 'Motion Pictures And Film']
sic_codes = ['7311']

In [79]:
#Read in Data
df_second=get_data('./raw_data/Adgency-7311_SecondPriority.csv')

#display the dimension of the data
dim=df_second.shape
print(f"The data has {dim[0]} rows and {dim[1]} columns")

The data has 100000 rows and 42 columns

In [80]:
df_second.copy().COMPANY_SIC

0                      7311;  8721
1                             7311
2                             7311
3               5092;  6531;  7311
4                      5963;  7311
                   ...
99995           7311;  8099;  8733
99996    2754;  2782;  7311;  7319
99997                  7311;  8743
99998           6411;  6531;  7311
99999                  5113;  7311
Name: COMPANY_SIC, Length: 100000, dtype: object

In [89]:
#check the effect of filter by sic code
filter_by_sic_codes(df_second.copy(),sic_codes).shape

(100000, 42)

In [90]:
#filter by industry
df_industry=filter_by_target_industries(df_second, target_industries)

In [91]:
#dimension
df_industry.shape

(64617, 42)

In [92]:
#validate
valid=validate_filter_by_target_industries_output(df_industry, target_industries)
valid

True

In [93]:
df_industry.PRIMARY_INDUSTRY.unique().tolist()

['Advertising Services',
 'Book And Periodical Publishing',
 'Entertainment Providers',
 'Events Services',
 'Broadcast Media Production And Distribution',
 'Movies, Videos, And Sound',
 'Spectator Sports',
 'Public Relations And Communications Services',
 'Online Audio And Video Media',
 'Printing Services',
 'Fundraising',
 'Newspaper Publishing',
 'Writing And Editing',
 'Animation And Post-Production',
 'Newspapers',
 'Sports',
 'Motion Pictures And Film']

In [94]:
#Check the list of sic code
df_industry.COMPANY_SIC.unique().tolist()

['7311;  8721',
 '7311',
 '5963;  7311',
 '6531;  7311',
 '2621;  7311',
 '7311;  7375',
 '2741;  7311',
 '7311;  8742',
 '7311;  7361;  8742',
 '7311;  7336',
 '7311;  7372',
 '2754;  2782;  7311;  7319',
 '7311;  8741',
 '4841;  7311;  7313',
 '2741;  7311;  7319',
 '4899;  7311',
 '5812;  7311;  7375',
 '5812;  7311;  8742',
 '7311;  8743',
 '2711;  7311',
 '5961;  7311;  7533',
 '7311;  7929',
 '7311;  7319',
 '7311;  7331;  8742',
 '2541;  7311;  7389',
 '6331;  7311;  9111',
 '7311;  7379;  7922',
 '1799;  7311',
 '3861;  5046;  7311',
 '2711;  2759;  5812;  7311',
 '4832;  5063;  7311;  7312',
 '5141;  7311',
 '6282;  7311;  7319',
 '5084;  7231;  7311',
 '1521;  7311',
 '5092;  7311',
 '7311;  7363',
 '7311;  8043',
 '2721;  7311',
 '7311;  8732;  8742',
 '3699;  7311',
 '7299;  7311',
 '7311;  7319;  7374',
 '7311;  8711',
 '4813;  7311;  7812',
 '4481;  7311;  8743',
 '7311;  7922;  8211',
 '1711;  4899;  7311',
 '4841;  6324;  7311;  8743',
 '7311;  7373;  7389;  8742',
 '7311;  8748',
 '4832;  6411;  7311',
 '7221;  7311',
 '2752;  7311',
 '2759;  7311',
 '4832;  7311',
 '7311;  7389',
 '3462;  7311',
 '7311;  8111',
 '4899;  5734;  7311',
 '6531;  7311;  7371',
 '3993;  7311',
 '6719;  7311',
 '7311;  8661;  8742',
 '7311;  8062;  8211',
 '7311;  7812',
 '2879;  7311',
 '7311;  7336;  8742',
 '7231;  7311',
 '7311;  8211;  8299',
 '2711;  6531;  7311',
 '0181;  7311;  8711',
 '7311;  7361',
 '2731;  7311',
 '7311;  7371',
 '5091;  7311;  7991',
 '3441;  7311;  8062',
 '7311;  8011',
 '2711;  2731;  7311',
 '6211;  7311;  7389;  8748',
 '4833;  7311',
 '5541;  7311',
 '7311;  7374',
 '2752;  7311;  8211',
 '7311;  7312',
 '7311;  8732',
 '3443;  7311',
 '2721;  7311;  8621',
 '5812;  7311',
 '7311;  8299',
 '7311;  7374;  8742',
 '5812;  6282;  7311;  8099',
 '1761;  7311;  7336',
 '7311;  8211',
 '2869;  5961;  7311',
 '5085;  7311;  7374',
 '7311;  8062',
 '7311;  7373;  8399',
 '5093;  7311',
 '6162;  7311',
 '6022;  7311;  7374;  7389',
 '3273;  7311;  8742',
 '7311;  7331',
 '5045;  7311',
 '4724;  7311',
 '7311;  8743;  8748',
 '5199;  7311;  7319',
 '5147;  7311;  8712;  8742',
 '7311;  7334',
 '2711;  7311;  7313',
 '3053;  7311',
 '6512;  7311;  8742',
 '7311;  7812;  8711',
 '7311;  8712;  8742',
 '7311;  7991',
 '7311;  7389;  8732',
 '7311;  7312;  7319',
 '7311;  7371;  7374',
 '7311;  8742;  8748',
 '4813;  7311;  7389',
 '4731;  6163;  7311',
 '3999;  7311;  8742',
 '7311;  8099',
 '7311;  8811',
 '3678;  7311;  7313;  7374',
 '2389;  7311',
 '6211;  7311;  8742',
 '4789;  7311;  8742',
 '2741;  5961;  7311',
 '5192;  7311;  8743',
 '2711;  7311;  7373',
 '3354;  7311;  7313',
 '6722;  7311',
 '3993;  7311;  7313',
 '5113;  7311',
 '7311;  7372;  7379',
 '2711;  5192;  6513;  7311',
 '7311;  8041',
 '7311;  7319;  7699;  8742',
 '5942;  7311;  8221',
 '4731;  7311',
 '7311;  7379',
 '3825;  7311;  7941',
 '7311;  7373',
 '7311;  7941',
 '7311;  9531',
 '7311;  8742;  8743',
 '7311;  7372;  8748',
 '5632;  7311;  7319;  7379;  7389',
 '5812;  5813;  7311',
 '1752;  5199;  7311',
 '7311;  7313',
 '5084;  7311',
 '5083;  7311',
 '2711;  3679;  7311',
 '1542;  7311',
 '2844;  7311',
 '2721;  5192;  7311',
 '7311;  8299;  8322;  8733',
 '4899;  7311;  7313;  7373;  7379',
 '7311;  8071;  8221',
 '5651;  7311',
 '6513;  7311',
 '1751;  7311',
 '5813;  7311;  7389',
 '5149;  7311;  8732',
 '2759;  7311;  7336',
 '7311;  8211;  8742',
 '7311;  7372;  7373;  8111',
 '2721;  7311;  7371',
 '7311;  8712',
 '5661;  7311',
 '7311;  7389;  8742',
 '1542;  7311;  8331',
 '4142;  7311',
 '5012;  7311',
 '7011;  7311;  8741',
 '7011;  7311',
 '5199;  7311',
 '2752;  7311;  8999',
 '7311;  8322',
 '5099;  7311',
 '7311;  7375;  8742',
 '7311;  7699;  8742',
 '7311;  7372;  8641',
 '7311;  8741;  8748',
 '7311;  7319;  7389',
 '3443;  7311;  8742',
 '7311;  7922',
 '4226;  7311',
 '7311;  7997',
 '4832;  4841;  7311',
 '2329;  7311;  7336',
 '3569;  3993;  7311',
 '5632;  7311',
 '7311;  8221;  8743',
 '6411;  7311',
 '6512;  7311',
 '2711;  6719;  7311',
 '5271;  7311',
 '4813;  7311;  8743',
 '7311;  7382',
 '4841;  7311;  8743',
 '6162;  7311;  7373',
 '4812;  7311;  7363',
 '7311;  7381;  8742',
 '6799;  7311',
 '6211;  7311;  7336;  8742',
 '7311;  7361;  8611',
 '2741;  5992;  7311',
 '5143;  7311;  7336',
 '6513;  7311;  8748',
 '2514;  7311',
 '4899;  7311;  8611',
 '6719;  7311;  7361',
 '7311;  8721;  8732;  8742',
 '1761;  7311',
 '5045;  7311;  7336;  7373;  8742',
 '5044;  7311',
 '5942;  7011;  7299;  7311',
 '5065;  7311',
 '5999;  7311;  8748',
 '2394;  7311;  8422;  8742',
 '7311;  8071',
 '2721;  2741;  7311;  7389',
 '7311;  8661',
 '2399;  7311',
 '5136;  5199;  7311',
 '2752;  7311;  8742',
 '5999;  7311',
 '7311;  7538',
 '4899;  7311;  8742',
 '7311;  8651',
 '2675;  3993;  4789;  7311',
 '5812;  6411;  7311;  7336',
 '7311;  7331;  8111',
 '5734;  7311',
 '7311;  8361',
 '7311;  7389;  8721',
 '6531;  7311;  7313',
 '5961;  7311',
 '7311;  8093',
 '4813;  7311',
 '5812;  7311;  7371',
 '7311;  7922;  8712;  8742',
 '7311;  8661;  8999',
 '5999;  7311;  8742',
 '7311;  9111',
 '7311;  7331;  7389',
 '7311;  7312;  8062;  8221',
 '6411;  7311;  7371',
 '2541;  7311;  8211',
 '3483;  7311',
 '7311;  7374;  7379',
 '7311;  7336;  7389',
 '3325;  7311;  8743',
 '6531;  7311;  8742',
 '5046;  7231;  7311',
 '7311;  7331;  7993',
 '3711;  7311',
 '6141;  7311;  7372',
 '4813;  7311;  7371;  7389',
 '7311;  8631',
 '4899;  5063;  7311',
 '3993;  7311;  7319;  7389',
 '5944;  7311',
 '7311;  7319;  7371',
 '7311;  7374;  8211',
 '5943;  7311',
 '6036;  7311;  8742',
 '5087;  7311;  7374',
 '4899;  5611;  7311',
 '5912;  7311',
 '4899;  7311;  7389',
 '6512;  7311;  7371',
 '7299;  7311;  7336',
 '6541;  7311',
 '2711;  2741;  5085;  7311',
 '5499;  7311',
 '1611;  6798;  7311;  7331',
 '2711;  7311;  8211',
 '5999;  6141;  7311;  7389',
 '5812;  7311;  8741',
 '6531;  7311;  7312',
 '7311;  7371;  7812',
 '6159;  7311',
 '0742;  7311',
 '7311;  8732;  8743',
 '1731;  7311',
 '7311;  8243;  8742',
 '2721;  7311;  8742',
 '5031;  7311;  7313',
 '5088;  5199;  7311',
 '1799;  7311;  8742',
 '5023;  7311',
 '1611;  7311;  7374',
 '3841;  7311',
 '4841;  7311',
 '5947;  7311;  7922;  8742',
 '5812;  7311;  7389',
 '3579;  5311;  7311;  8742',
 '3312;  7311;  7361',
 '2721;  7311;  7379',
 '2752;  7311;  7336',
 '3944;  7311;  7997',
 '4231;  7311;  7812',
 '7311;  7812;  8412',
 '5399;  7311',
 '3993;  7311;  8742',
 '7311;  7353;  7359;  7997',
 '5399;  7311;  8062',
 '5199;  7311;  8721',
 '2711;  2721;  7311',
 '2741;  5211;  7311',
 '6061;  6719;  7311;  7313',
 '5087;  7311',
 '4813;  7311;  7375',
 '6512;  7311;  8111',
 '5511;  7311',
 '7311;  7389;  8322',
 '5013;  7311',
 '3711;  7311;  8743',
 '7311;  7336;  7372',
 '2819;  7311',
 '5994;  7311',
 '7311;  7349;  7389',
 '5813;  7311;  8742',
 '6311;  7311',
 '5511;  6411;  7311',
 '5021;  6411;  7311',
 '5411;  7311',
 '6733;  7311',
 '7311;  8741;  8743',
 '7311;  7999;  8742',
 '2752;  2759;  7311',
 '4311;  7311',
 '2771;  7311',
 '7311;  8742;  9431',
 '6022;  7311',
 '7311;  7372;  7373',
 '7311;  8211;  8743',
 '7021;  7311;  7371',
 '7311;  8093;  8742',
 '7311;  7623',
 '7311;  8611',
 '7311;  8711;  8742',
 '5193;  7311',
 '4899;  7311;  7312',
 '1382;  7311',
 '4812;  5311;  7311',
 '7311;  7319;  7336;  7379',
 '2721;  7311;  7389',
 '5599;  7311',
 '4142;  4899;  7311;  8244',
 '5084;  7311;  7319',
 '2789;  7311;  7331',
 '4899;  7311;  7812',
 '0781;  7311',
 '7311;  7379;  8011',
 '7311;  8111;  8742',
 '5963;  7311;  7331',
 '7311;  7699;  8049',
 '6035;  7311',
 '3273;  7311',
 '3823;  7311;  7374',
 '7311;  7922;  7929',
 '5099;  5199;  7311',
 '2711;  2741;  7311',
 '7311;  8021',
 '4225;  5699;  7311;  7319',
 '5199;  7311;  8743',
 '7311;  8731',
 '0181;  7311',
 '5995;  7311',
 '2395;  7311',
 '7311;  7374;  7375',
 '1731;  4832;  7311',
 '6061;  7311;  8742',
 '7311;  7335;  8742',
 '2834;  7311',
 '2759;  5511;  7311;  7336',
 '5734;  7311;  8742',
 '5812;  7311;  7371;  8742',
 '7311;  7371;  8811',
 '1799;  5199;  7311',
 '5712;  7311',
 '5021;  7311;  8742',
 '6531;  7311;  8211',
 '4813;  7311;  7313',
 '7311;  8731;  8748;  8999',
 '7311;  7999',
 '6021;  7311',
 '7311;  8011;  8742',
 '1541;  7311;  8299',
 '5199;  7311;  7312',
 '1721;  5078;  7311',
 '7311;  8721;  8743',
 '5112;  7311',
 '3949;  6531;  7311',
 '5499;  5531;  7311',
 '1799;  4899;  7311',
 '0191;  7311',
 '3229;  5812;  7311',
 '1611;  5023;  7311',
 '4899;  7311;  8743',
 '2431;  7311;  8011',
 '5947;  7311',
 '1771;  7311',
 '3812;  7311;  7374;  8742',
 '7311;  7379;  7389',
 '7311;  7378',
 '1521;  7311;  8743',
 '4899;  7311;  7371',
 '5199;  7311;  8221',
 '7311;  7389;  7941;  8299',
 '4899;  7311;  8221',
 '7311;  9199',
 '2721;  2741;  7311',
 '7311;  7389;  8072',
 '6799;  7311;  8742',
 '3823;  7311;  8051',
 '4941;  7311',
 '5051;  7311',
 '7311;  7336;  8699',
 '7311;  8082',
 '5046;  7311;  7389',
 '7311;  8211;  8748',
 '6282;  7311;  8742',
 '0783;  7311;  8742',
 '3081;  7311;  7389;  8322',
 '4899;  6411;  7311',
 '7311;  7335;  7336',
 '6282;  7311',
 '2893;  7311;  8043;  8743',
 '4899;  7311;  8042',
 '7311;  8741;  8742',
 '5999;  7311;  7812',
 '4813;  4833;  7311',
 '3545;  5085;  7311',
 '4899;  7311;  7389;  8742',
 '3577;  7311;  8742',
 '5199;  7311;  7699;  8021',
 '7311;  7374;  7375;  8611',
 '5063;  5199;  7311',
 '7311;  8611;  8741',
 '5511;  5731;  7311',
 '3993;  4813;  7311',
 '7311;  7336;  8999',
 '4513;  7311;  7389',
 '1731;  7311;  7812',
 '7311;  7514',
 '3425;  4899;  7311',
 '4213;  7311;  8111',
 '5411;  7311;  8621',
 '2261;  7311',
 '4724;  7311;  7319',
 '3452;  7311',
 '5399;  7311;  8011',
 '5511;  5812;  7311',
 '7311;  7312;  8211',
 '7311;  7389;  8699',
 '7311;  7371;  7373',
 '5941;  7311',
 '7311;  7312;  7538',
 '6531;  7311;  8711',
 '5812;  5963;  7311',
 '7311;  9431',
 '2676;  7311',
 '7311;  7378;  7389',
 '7311;  8092',
 '2431;  7311',
 '2711;  4899;  7311',
 '7311;  7313;  8743',
 '3444;  7311',
 '1711;  7311',
 '5699;  7311',
 '6022;  7311;  8743',
 '5511;  7311;  7538',
 '2711;  3672;  7311',
 '4789;  7311',
 '5311;  7311',
 '7311;  7381',
 '7311;  7363;  7373',
 '5046;  7311;  8711',
 '7311;  7319;  7331',
 '2731;  7311;  8742',
 '7311;  7371;  7389',
 '7311;  7336;  7371',
 '5946;  7311;  7353',
 '7261;  7311',
 '5963;  7311;  8093',
 '5199;  5251;  7311',
 '2511;  3599;  7311',
 '5712;  7311;  8742',
 '7311;  7319;  8731',
 '2813;  7311;  8721',
 '7216;  7311',
 '2754;  7311',
 '5813;  7311',
 '4841;  7311;  7336',
 '7311;  9223',
 '7311;  8999',
 '7311;  7313;  8742',
 '3823;  7311',
 '7311;  7822',
 '6531;  7311;  8734',
 '5172;  7311',
 '7311;  7373;  8742',
 '3089;  7311',
 '7311;  8062;  8743',
 '1731;  7311;  7389',
 '3089;  5112;  7311',
 '6141;  7311',
 '3599;  5045;  7311',
 '4225;  7311;  7319',
 '5912;  7311;  8742',
 '5094;  7311',
 '5411;  5736;  7311',
 '4832;  4833;  7311;  8731',
 '7311;  7375;  8999',
 '3714;  7311',
 '4812;  7311;  7371',
 '5942;  7311;  7336',
 '2741;  3845;  7311',
 '7311;  8231',
 '7311;  8211;  9121',
 '7311;  7331;  8743',
 '2711;  2752;  7311',
 '5199;  7311;  7389',
 '7311;  8051;  8748',
 '7311;  8734',
 '7311;  8299;  8748',
 '5013;  6531;  7311',
 '2711;  7311;  7812',
 '6162;  7311;  8742',
 '7311;  7699;  8743',
 '5199;  7311;  8399',
 '7311;  8062;  8748',
 '6022;  7311;  7336;  8742',
 '7231;  7311;  7997',
 '4581;  7311',
 '7311;  7922;  8741',
 '6061;  7311',
 '6411;  7311;  8742',
 '4899;  5812;  7311',
 '5032;  7311;  7371',
 '7311;  7336;  8211',
 '4899;  7311;  7336',
 '4812;  7311',
 '6531;  7311;  7389',
 '5941;  7311;  8721',
 '7311;  7922;  8742',
 '2741;  3715;  7311',
 '6799;  7311;  7373;  8043',
 '4899;  7311;  7319',
 '7231;  7311;  7929;  8713;  8741',
 '5084;  7311;  7371',
 '7311;  8322;  8742',
 '7311;  8713;  8742',
 '7311;  8111;  8748',
 '5193;  5311;  7311;  7389',
 '4212;  7311',
 '5983;  7311;  8742',
 '5983;  7311;  8322;  8748',
 '7311;  7372;  8742',
 '5949;  7311',
 '5199;  5712;  7311',
 '4833;  7311;  7389',
 '7311;  7997;  8211',
 '5099;  5736;  7311',
 '4131;  7311;  8999',
 '3826;  5311;  7311',
 '0742;  7311;  7319',
 '3829;  7311;  7374',
 '6321;  7311',
 '7261;  7311;  8742',
 '6411;  7311;  7312;  7336',
 '0119;  3812;  5065;  7311;  7313',
 '7311;  7819',
 '7311;  8011;  8741',
 '2741;  7311;  7389',
 '2741;  4832;  7311;  7812',
 '5084;  7311;  7322',
 '7311;  8211;  8322',
 '7311;  7371;  8742',
 '3944;  5211;  7311',
 '5199;  7299;  7311',
 '4215;  7311',
 '2711;  7311;  8011',
 '5122;  7311;  8069',
 '2741;  7311;  8661',
 '6399;  7311;  7313',
 '7311;  7812;  7922',
 '4899;  7311;  7335',
 '7311;  7361;  7375',
 '2741;  7311;  8111;  9441',
 '7311;  7349',
 '4215;  7311;  8742',
 '6282;  7311;  7371;  8742',
 '3822;  7311',
 '5084;  7311;  7331;  8742',
 '4813;  6531;  7311',
 '2711;  5088;  7311;  8082',
 '7311;  8711;  8743',
 '2514;  2711;  7311;  7319',
 '7311;  7371;  7819',
 '7311;  7382;  8742',
 '2711;  5942;  7311',
 '7311;  7538;  8742',
 '2721;  6021;  7311;  7389',
 '1743;  7311',
 '4783;  7311;  7389',
 '7311;  7313;  7371',
 '0191;  2721;  7311',
 '1799;  2834;  7311;  7371',
 '5211;  7311;  7622',
 '2541;  5046;  7311',
 '1752;  7311;  7538',
 '7311;  8051',
 '5999;  7311;  7389;  8011',
 '7033;  7311;  8748',
 '5311;  7311;  7389',
 '6061;  7311;  8712',
 '7311;  7313;  7319',
 '4813;  7311;  7379',
 '7311;  7832',
 '7311;  7997;  8742',
 '1721;  7311',
 '7311;  7322',
 '7311;  7389;  7812',
 '5984;  7311;  7336',
 '1711;  6512;  7311;  7379;  8742',
 '7311;  7812;  8051',
 '7311;  8082;  8743',
 '2821;  7311;  7371',
 '7311;  7371;  8748',
 '7311;  7389;  8743',
 '3841;  7311;  8743',
 '7311;  8641;  8742',
 '5074;  7311',
 '2099;  7311',
 '1629;  7311;  8742',
 '2752;  2791;  7311',
 '7311;  8059;  8748',
 '4512;  7311',
 '1761;  2741;  7311',
 '6153;  7311',
 '4832;  7311;  8099',
 '5731;  7311',
 '5461;  5812;  7311',
 '3993;  7311;  7312',
 '6531;  6552;  7311',
 '7311;  8351;  8742',
 '2084;  7311;  8748',
 '5199;  5812;  7311;  7319',
 '5082;  7311',
 '5812;  5944;  7311;  7922',
 '7311;  7359;  7812',
 '7311;  7349;  7379',
 '7299;  7311;  8742',
 '6719;  7311;  7336;  7374',
 '2759;  5199;  7311',
 '2752;  4899;  7311;  7374',
 '2086;  5199;  7311',
 '5812;  6531;  7311;  8742',
 '2759;  7311;  7371',
 '3599;  7311',
 '6411;  7311;  8111',
 '5812;  6719;  7311',
 '7311;  7371;  7373;  7991',
 '7311;  7373;  8743',
 '4832;  7311;  7372',
 '0752;  7311',
 '5999;  7311;  8399',
 '4215;  7311;  7336',
 '7311;  8731;  8742',
 '2711;  7311;  8742',
 '7311;  8699',
 '3589;  7311;  8742',
 '1521;  7311;  8082',
 '7311;  7371;  7389;  8742',
 '6531;  7311;  8069',
 '7311;  8072',
 '2499;  5813;  7311',
 '2396;  5199;  7311',
 '6531;  7311;  7319',
 '5136;  7311',
 '3679;  7311',
 '5182;  7311',
 '2759;  7311;  8211',
 '3661;  7311',
 '3634;  7311;  8742',
 '7311;  7371;  8082',
 '5199;  7311;  8732',
 '1389;  7311;  7312',
 '6531;  7311;  7389;  8743',
 '1794;  7311;  8742',
 '5511;  7311;  7379',
 '1711;  5731;  6531;  7311',
 '7311;  7335;  7371',
 '5199;  5651;  7311;  8732',
 '7311;  9211',
 '7311;  7313;  7389',
 '7311;  7699;  8999',
 '3523;  7311;  8713',
 '7311;  8641',
 '2711;  5192;  7311',
 '5211;  7311',
 '6211;  7311',
 '7311;  8733',
 '4899;  7311;  8748',
 '2731;  2741;  7311',
 '4832;  7311;  8211',
 '5199;  6099;  7311',
 '2752;  2759;  7311;  8711',
 '3993;  5199;  7311',
 '3993;  5046;  7311',
 '7311;  7379;  7996',
 '2429;  7311',
 '2411;  7311;  8742',
 '7311;  7389;  8021',
 '7311;  7322;  8742',
 '4225;  7311;  7363;  8111',
 '5199;  7311;  7822;  8742',
 '7311;  8059',
 '4899;  6153;  7311',
 '7311;  7389;  8111',
 '4832;  7311;  7313',
 '0182;  7311',
 '7311;  7812;  7819',
 '2711;  5331;  7311',
 '3565;  7311',
 '3695;  7311',
 '2711;  7311;  8748',
 '4899;  6719;  7311;  7312',
 '2741;  7311;  7331',
 '5251;  6512;  7311',
 '4899;  7311;  8811',
 '4226;  7311;  7319',
 '3651;  7311',
 '6552;  7311;  8811',
 '7311;  8221',
 '7311;  7336;  8111',
 '2732;  2752;  7311;  8111',
 '1711;  7311;  7312',
 '1542;  2789;  3999;  5511;  7311',
 '5812;  6211;  7311',
 '5192;  7311',
 '7311;  7319;  8742',
 '7311;  7313;  7812',
 '7011;  7311;  7374',
 '1799;  4724;  7311',
 '5699;  7311;  7336',
 '7311;  7319;  8741',
 '1611;  7311',
 '7311;  8099;  8742',
 '5199;  6512;  7311',
 '2541;  3993;  7311;  8741',
 '7311;  8699;  8742',
 '7311;  7319;  8249',
 '5812;  5999;  7311',
 '7311;  8742;  8811',
 '5521;  7311',
 '1629;  7311',
 '3663;  7311;  8743',
 '7291;  7311',
 '7311;  7313;  7336;  8742',
 '2653;  7311',
 '3571;  7311',
 '5199;  7311;  8399;  8742',
 '5142;  7311;  9111',
 '6799;  7311;  7822',
 '3999;  7311;  8211',
 '2051;  7311;  8742',
 '7311;  7374;  8222;  8741',
 '5084;  7311;  7389',
 '4119;  7311',
 '2752;  7311;  7312',
 '1623;  7311',
 '2741;  5999;  7311',
 '7311;  7699',
 '5137;  7311',
 '5713;  7311',
 '5331;  7311',
 '3843;  7311',
 '4899;  7311;  8093',
 '3429;  7311',
 '5712;  7311;  7336;  7379',
 '2741;  5199;  7311',
 '2741;  7311;  7336;  7373',
 '2759;  5511;  7311',
 '7311;  8011;  8743',
 '7311;  8621',
 '5421;  7311;  8661',
 '0971;  4832;  7311',
 '2711;  4813;  7311',
 '5099;  7311;  7312;  7359',
 '7033;  7311',
 '3432;  4833;  7311',
 '7311;  8742;  9111',
 '4899;  7311;  7812;  8741',
 '3549;  7311',
 '7311;  7336;  9631',
 '5231;  7311',
 '2519;  7311;  7812',
 '3599;  7311;  7374',
 '3149;  7311',
 '2731;  5942;  7311',
 '6061;  7311;  8111',
 '7311;  8399',
 '7011;  7311;  7997;  8322',
 '5113;  7311;  8742',
 '6512;  7311;  7336',
 '7311;  7312;  8011',
 '5045;  7311;  7372',
 '7311;  7313;  8711',
 '7311;  7389;  8748',
 '7311;  7336;  7373',
 '5112;  6512;  7311',
 '5193;  6531;  7311',
 '7311;  9711',
 '2253;  7311;  8742',
 '5511;  7311;  8748',
 '7311;  8042',
 '7311;  7373;  8011',
 '2759;  6411;  7311',
 '5511;  7311;  7319',
 '5451;  7311',
 '1731;  7311;  7372;  8742',
 '0742;  7311;  8742',
 '5999;  6211;  7311',
 '5541;  7311;  8742',
 '7311;  8422;  8742',
 '3643;  5148;  5961;  7311',
 '2759;  7311;  7389',
 '6719;  7311;  8742',
 '5812;  7311;  7336',
 '5046;  7311',
 '7311;  8222',
 '5961;  7311;  8742',
 '2759;  4225;  7311',
 '5085;  7311',
 '5621;  7311',
 '7311;  7389;  7822',
 '5993;  7311',
 '7311;  7373;  7379',
 '1731;  4899;  7311',
 '5651;  7311;  8742',
 '2791;  6512;  7311',
 '5945;  7311;  7389',
 '5141;  7311;  8742',
 '2752;  2759;  2822;  7311',
 '2711;  5963;  7311',
 '7311;  7371;  7373;  8711',
 '4899;  7311;  8211',
 '7311;  8049',
 '7311;  7379;  8742',
 '7311;  7381;  8711',
 '1711;  7311;  8062;  8742',
 '7311;  8043;  8742',
 '4813;  7311;  7371;  9611',
 '7311;  7336;  8011',
 '7311;  7812;  8611',
 '7311;  7372;  7373;  7991',
 '7311;  7319;  7359',
 '7311;  7312;  8661',
 '7311;  8249',
 '2752;  2754;  7311',
 '3353;  7311',
 '5511;  7311;  8661',
 '7311;  7373;  7389',
 '2053;  7311',
 '5511;  7311;  7389',
 '7311;  8399;  8711',
 '7311;  7335',
 '5099;  7311;  7359;  8748',
 '4213;  7311',
 '5812;  7311;  7999',
 '2754;  5999;  7311',
 '7311;  8111;  8741',
 '6512;  7311;  8661',
 '7311;  8412',
 '7299;  7311;  8743',
 '4212;  7311;  8742',
 '7311;  7929;  8742',
 '5932;  7311',
 '7311;  8742;  9224',
 '6162;  7311;  8721',
 '7299;  7311;  7389',
 '7311;  7319;  8733',
 '5191;  7311;  8351',
 '4899;  6512;  7311;  7372',
 '5065;  7311;  9111',
 '3826;  7311',
 '6513;  7311;  7371;  8742',
 '7311;  7629',
 '2711;  7311;  7371',
 '3851;  7311;  7372',
 '3761;  7311;  7812',
 '4833;  7311;  8742',
 '2759;  6799;  7311',
 '3674;  7311;  7336',
 '7311;  7313;  8111',
 '2752;  7311;  7336;  7371',
 '3674;  7311',
 '7311;  7319;  8699;  9221',
 '7311;  7319;  8661',
 '0212;  7311',
 '4725;  7311;  7389',
 '5074;  5311;  7311;  7313',
 '7311;  7911',
 '5311;  6531;  7311',
 '2741;  4899;  7311;  7374',
 '5599;  7311;  7319',
 '6513;  7311;  7336',
 '2335;  7299;  7311',
 '4813;  7311;  8742',
 '7311;  8099;  9441',
 '7311;  7319;  7363',
 '5092;  5199;  7311',

In [138]:
# def filter_by_valid_business_personal_email(df, validation_column="BUSINESS_EMAIL_VALIDATION_STATUS", business_email_column="BUSINESS_EMAIL", personal_email_column="PERSONAL_EMAIL"):
#     """
#     [Function Description]
#     """
#     df_processed = df.copy()

#     # Determine whether each business email is valid
#     is_valid = df_processed[validation_column].str.contains("Valid", case=False, na=False)

#     def get_valid_email(business_email, personal_emails, is_valid_email):
#         if is_valid_email:
#             return business_email
#         else:
#             personal_emails_list = personal_emails.split(',') if isinstance(personal_emails, str) else [personal_emails]
#             # Select an alternate personal email if available, or the first one in the list
#             return personal_emails_list[1] if len(personal_emails_list) > 1 else personal_emails_list[0]

#     df_processed['Valid_Business_Email'] = df_processed.apply(lambda row: get_valid_email(row[business_email_column], row[personal_email_column], is_valid[row.name]), axis=1)

#     return df_processed

In [139]:
#Filter by Valid Busines email
Email_7311_list=filter_by_valid_business_personal_email(
    df=df_industry,
    validation_column="BUSINESS_EMAIL_VALIDATION_STATUS",
    business_email_column="BUSINESS_EMAIL",
    personal_email_column="PERSONAL_EMAIL"
)

In [140]:
# check the size of your data
Email_7311_list.shape

(64617, 43)

In [124]:
#drop empty rows in vaid business email
email_list_7311=drop_rows_with_hyphen(Email_7311_list, "Valid_Business_Email")

In [141]:
#enrich email values
list_emial_phone=enrich_phone_numbers(email_list_7311)

In [142]:
list_emial_phone[['FIRST_NAME','LAST_NAME','Valid_Business_Email',"ENRICHED_PHONE_NUMBER"]]

,FIRST_NAME,LAST_NAME,Valid_Business_Email,ENRICHED_PHONE_NUMBER
0,Nhora,Murphy,nmurphy@tmncorp.com,+13014680956
7,Junia,Bauer,craig.buell@yahoo.com,+12033562496
13,Keith,Kan,asideat52@yahoo.com,+17035735754
16,Angela,Strain,star_to_star2001@yahoo.co.in,+14097242203
21,Annis,Kishner,annisekishner447@yahoo.com,+14048127000
...,...,...,...,...
99989,Rishi,Doshi,rdoshi@horizonmedia.com,+12122204916
99990,Bonnie,Overton,saphire0777@gmail.com,+19194630330
99991,Emily,Hean,emily.hean@rapp.com,+15033481744
99994,Greg,George,snowgrains@yahoo.com,+13126162339
99997,Caroline,Kenne,alexandriagrey@comcast.net,+16172049500

In [143]:
valid_email_columns=['FIRST_NAME','LAST_NAME','Valid_Business_Email',"ENRICHED_PHONE_NUMBER"]
email=list_emial_phone[valid_email_columns]

In [ ]:
     output_row = {
                    'Client Customer ID': client_customer_id_counter,
                    'First Name': row.get('FIRST_NAME', ''),
                    'Last Name': row.get('LAST_NAME', ''),
                    'Street Address 1': valid_address1 or valid_address2 or valid_address3,
                    'Street Address 2': valid_address1 or valid_address2 or valid_address3,
                    'City': row.get('PERSONAL_CITY', ''),
                    'State': state_column,
                    'Zip Code': row.get('PERSONAL_ZIP', ''),
                    'Zip Code Plus 4': row.get('PERSONAL_ZIP4', ''),
                    'Email1': row.get('PERSONAL_EMAIL', ''),
                    'Email2': row.get('BUSINESS_EMAIL', ''),
                    'Email3': row.get('BUSINESS_EMAIL', ''),  # Assuming Email3 is from BUSINESS_EMAIL
                    'PhoneNumber1': row.get('DIRECT_NUMBER', ''),
                    'PhoneNumber2': row.get('MOBILE_PHONE', '')
                }

In [144]:
email.shape

(33874, 4)

In [84]:
save_df_to_csv(email, "email_phone_7311_list2")

DataFrame successfully saved to Output_list_DataBase\email_phone_7311_list2.csv

In [21]:
merge_csv_files("./merger_input_data","./output_list_database/combined_emai_list.csv",['Valid_Business_Email'])

Merged data saved to './output_list_database/combined_emai_list.csv' and duplicates removed.

In [23]:
get_data('output_list_database\combined_emai_list.csv').shape

(49194, 4)